name: Cargo build

on:
    workflow_call:
        inputs:
            build-os:
                description: os to build
                required: false
                type: string
                default: |
                    [{"os": "ubuntu-latest"},
                    {"os": "macOS-latest"},
                    {"os": "windows-latest"}]

defaults:
    run:
        shell: bash
        
env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        name: Build on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
              include: ${{fromJSON(inputs.build-os)}}
        steps:
            - uses: actions/checkout@v4
            - name: install bevy dependencies
              run: |
                if [ ${{ matrix.os }} == ubuntu-latest ]; then
                    sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 -y
                fi
            - name: Building project
              run: cargo build --verbose